title: Data Science I
author: the University of Chicago
copyright: "2022"
logo: ""  # path to a logo file

sphinx:
  config:
    execution_show_tb: true
  extra_extensions:
    - sphinx_proof

execute:
  timeout: 100

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_image
