title: Introduction to Data Science I & II
author: the University of Chicago
copyright: "2022"
logo: "images/logo/uchicago_python_nobackground.png"  # path to a logo file
only_build_toc_files: true

sphinx:
  config:
    nb_execution_show_tb: true
    html_favicon: favicon.ico
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
  extra_extensions:
    - sphinx_proof
    - sphinx_multitoc_numbering

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - deflist
    - html_image

html:
  extra_js:
    - glossary-sidebar.js